site_name: Numériques et Sciences Informatiques Lycée
site_description: Cours de NSI  du lycée Hintermann-Afféjee
site_author: Fabrice NATIVEL

docs_dir: docs

nav:
- "<img src='https://fabricenativel.github.io/icones/home.svg' width=16px height=16px>&thinsp; Accueil" :
    - index.md
- "<img src='https://fabricenativel.github.io/icones/checklist-16.svg' width=16px height=16px>&thinsp; Cours de première" :
      - "Index" : Premiere/progression.md
      - "C1-Systèmes d'exploitation" : Premiere/os.md
      - "C2-Représentation des entiers et des caractères" : Premiere/codage.md
      - "C3-Initiation à Python avec Turtle - Partie 1" : Premiere/ippt1.md
      - "C4-Architecture matérielle" : Premiere/architecture.md
      - "C5-Initiation à Python avec Turtle - Partie 2" : Premiere/ippt2.md
      - "C6-Notions d'algorithmique" : Premiere/notionsalgo.md
      - "C7-Lecture et traitement de données en table" : Premiere/donneestable.md
      - "C8-Le web" : Premiere/leweb.md
      - "C9-Algorithmes de tri" : Premiere/algostri.md
      - "C10-Représentation des entiers négatifs" : Premiere/negatifs.md
      - "C11-Réseau" : Premiere/reseau.md
      - "C12-Interaction dans une page web" : Premiere/interactionweb.md
      - "C13-Algorithmes gloutons" : Premiere/gloutons.md
      - "C14-Fusion de tables" : Premiere/fusiontable.md
      - "C15-Interface homme-machine" : Premiere/interface.md
      - "C16-Notion de nombre flottant" : Premiere/flottant.md
      - "C17-Algorithme des k plus proches voisins" : Premiere/knn.md
- "<img src='https://fabricenativel.github.io/icones/list-ordered-16.svg' width=16px height=16px>&thinsp; Cours de terminale" :
      - "Index" : Terminale/progression.md
      - "C0-Révisions" : Terminale/revisions.md
      - "C1-Récursivité" : Terminale/recursivite.md
      - "C2-Bases de données et SQL" : Terminale/sql.md
      - "C3-Processus" : Terminale/processus.md
      - "C4-Diviser pour régner" : Terminale/diviser.md
      - "C5-Notions de programmation orienté objet" : Terminale/poo.md
      - "C6-Structures de données linéaires" : Terminale/sl.md
      - "C7-Système sur puce" : Terminale/puces.md
      - "C8-Arbres" : Terminale/arbres.md
      - "C9-Schéma relationnel d'une base de données" : Terminale/sgbd.md
      - "C10-Algorithmes sur les arbres" : Terminale/algoarbre.md
      - "C11-Graphes" : Terminale/graphes.md
      - "C12-Protocoles de routage" : Terminale/routage.md
      - "C13-Recherche textuelle" : Terminale/texte.md
      - "C14-Calculabilité, décidabilité" : Terminale/calculabilite.md
      - "C15-Sécurisation des communications" : Terminale/cryptographie.md
- "<img src='https://fabricenativel.github.io/icones/file-badge-16.svg' width=16px height=16px>&thinsp; Documents officiels" :
    - officiels.md
- "<img src='https://fabricenativel.github.io/icones/graduation-cap.svg' width=16px height=16px>&thinsp; Annales du Bac" :
    - index_annales.md
    - '2021': 
      - "Epreuves écrites" : Terminale/Annales/2021/EE.md
      - "Epreuves pratiques" : Terminale/Annales/2021/EP.md
    - '2022': 
      - "Epreuves écrites" : Terminale/Annales/2022/EE.md
      - "Epreuves pratiques" : Terminale/Annales/2022/EP.md
- "<img src='https://fabricenativel.github.io/icones/lightbulb.svg' width=16px height=16px>&thinsp; Projets" :
    - "Projets" : projets.md
    - "Projets de Première" :
      - "Morpion" : Premiere/projets/morpion.md
      - "Cryptographie" : Premiere/projets/cryptographie.md
      - "Force brute" : Premiere/projets/forcebrute.md
      - "Jeu avec Pyxel" : Premiere/projets/pyxel.md
      - "Steganographie" : Premiere/projets/steganographie.md
    - "Projets de Terminale" : 
      - "Gomoku" : Terminale/projets/gomoku.md
      - "POO et Réseau" : Terminale/projets/reseau.md
      - "Les 8 reines" : Terminale/projets/reines.md
      - "Jeu avec Pyxel" : Terminale/projets/pyxel.md
- "<img src='https://fabricenativel.github.io/icones/links.svg' width=16px height=16px>&thinsp; Liens" :
    - liens.md
- "<img src='https://fabricenativel.github.io/icones/python.svg' width=16px height=16px>&thinsp; Python" :
    - python.md
- "<img src='https://fabricenativel.github.io/icones/information.svg' width=16px height=16px>&thinsp; A propos" :
    - apropos.md

theme:
    favicon: images/favicon.ico
    icon:
      logo: fontawesome/solid/dragon

    custom_dir: overrides

    name: material
    language: fr                    # français
    palette:                        # Palettes de couleurs jour/nuit
      scheme: default

    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - content.code.annotate 
      - navigation.expand


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:          # Imbrication de blocs.
    # Exception pour code highlight (de façon à faire fonctionner mermaid)
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true          # Volets glissants.  === "Mon volet"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.

  - attr_list
  # Permet l'utilisation d'abbréviation dans le fichier syntaxe *[abbr]: description (voir glossaire.md)
  - abbr
  # Permet l'insertion de fichiers dans le document à l'aide de la syntaxe --8<-- "includes/glossaire.md"
  - pymdownx.snippets
  # Admonitions et variantes (details : repliable, superfences : avec onglet)
  - admonition
  - pymdownx.details
  - pymdownx.keys:
      strict: false


plugins:
  - search
  - macros

extra_javascript:
  - javascript/config.js                    # MathJax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/fenarius.css